#!/usr/bin/env bash
set -e

# Cleanup
rm -rf dist es

echo 'Compile JS...'
rollup -c scripts/rollup.config.js
echo 'Done.'
echo ''

echo 'Build ES modules...'
npx babel src --out-dir es
echo 'Done.'
echo ''

echo 'Minify JS...'
terser dist/ripecss-vue.js \
       --compress typeofs=false \
       --mangle --comments "/^!/" \
       --source-map "content=dist/ripecss-vue.js.map,includeSources,url=ripecss-vue.min.js.map" \
       --output dist/ripecss-vue.min.js
terser dist/ripecss-vue.common.js \
       --compress typeofs=false \
       --mangle --comments "/^!/" \
       --source-map "content=dist/ripecss-vue.common.js.map,includeSources,url=ripecss-vue.common.min.js.map" \
       --output dist/ripecss-vue.common.min.js
terser dist/ripecss-vue.esm.js \
       --compress typeofs=false \
       --mangle \
       --comments "/^!/" \
       --source-map "content=dist/ripecss-vue.esm.js.map,includeSources,url=ripecss-vue.esm.min.js.map" \
       --output dist/ripecss-vue.esm.min.js
echo 'Done.'
echo ''

echo 'Compile SASS...'
node-sass --output-style expanded \
          --source-map true \
          --source-map-contents true \
          --precision 6 \
          src/index.scss \
          dist/ripecss-vue.css
postcss --config scripts/postcss.config.js \
        --replace dist/ripecss-vue.css
echo 'Done.'
echo ''

echo 'Minify CSS...'
cleancss --level 1 \
         --format breaksWith=lf \
         --source-map \
         --source-map-inline-sources \
         --output dist/ripecss-vue.min.css \
         dist/ripecss-vue.css
echo 'Done.'
echo ''

echo 'Done building assets.'
